name: CI Basics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    name: Basic CI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository structure
        run: |
          pwd
          ls -la

      - name: Check installed tools
        run: |
          git --version
          bash --version
  sast:
    name: SAST - SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: app/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker_build_scan_and_publish:
    name: Build Docker Image Scan and publish
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devsecops-lab:latest app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: devsecops-lab:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Tag Docker image with commit SHA
        run: |
          docker tag devsecops-lab:latest jagathees007/devsecops-lab:${{ github.sha }}


      - name: Tag Docker image with commit SHA
        run: |
          docker tag devsecops-lab:latest jagathees007/devsecops-lab:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push jagathees007/devsecops-lab:${{ github.sha }}
          docker push jagathees007/devsecops-lab:latest
